### ISSUE TITLE
Invalid left-hand side in assignment (Angular)

### ISSUE THREAD

**Issue by kisimediaDE** [michelonsouza/encrypt-storage#640]
Hey 😃 

the bug from #583 is still in the current version of the plugin. 
People (including me) are very confused about it. Because in your comment you wrote that you promise a fix in the next version but the added tag is saying WON'T FIX. 

Since the issue is closed and still people are commenting it I open this issue to continue the talk. 

Hope you have a good week and greetings!

**Comment by lbetancourtoliva** [comment]
I get the same issue with the latest version @michelonsouza.
Greetings.

**Comment by michelonsouza** [comment]
I'm sorry about that guys.... I promise I'll fix it ASAP

**Comment by ravi-mone** [comment]
@michelonsouza , Can you please fix this , after a long long debugging process I got to know this error is from this encryption package, Can you please fix ASAP, please

**Comment by ravi-mone** [comment]
@kisimediaDE , 
 it is like this 
 window.a = 1; //This will not throw error
window?.a = 1; //But this will throw error `Uncaught SyntaxError: Invalid left-hand side in assignment`

**Comment by ravi-mone** [comment]
@kisimediaDE thanks for that, it was quick. thanks a ton

**Comment by kisimediaDE** [comment]
@ravi-mone dependencies updates. Nothing relevant from function perspective.

**Comment by michelonsouza** [comment]
I would like to apologize for my absence. It's been a busy few weeks, but now I'm back.
I fixed the issue and hope to have good news from testing in version 2.12.17.

Thank you all and again, I'm sorry.

**Comment by kisimediaDE** [comment]
Hey, no problem, we're all more than happy that you're even doing the work to develop such a great product in your spare time. And even without the update, the plugin worked in an old version.

I just updated and deployed my project.  I no longer get an error message and your latest update works perfectly.

Thank you so much and have a great day!!! 😄

**Comment by yellowjacketcoder** [comment]
@michelonsouza This issue still exists in latest version 2.12.22

@kisimediaDE How did you get this to work with Angular 15?
